Disable android ndk detection

diff --git a/mozjs/js/src/old-configure b/mozjs/js/src/old-configure
--- a/mozjs/js/src/old-configure
+++ b/mozjs/js/src/old-configure
@@ -1162,11 +1162,11 @@ echo "configure:1144: checking for android platform directory" >&5
 
     android_platform="$android_ndk"/platforms/android-"$android_version"/arch-"$target_name"
 
-    if test -d "$android_platform" ; then
-        echo "$ac_t""$android_platform" 1>&6
-    else
-        { echo "configure: error: not found. Please check your NDK. With the current configuration, it should be in $android_platform" 1>&2; echo "configure: error: not found. Please check your NDK. With the current configuration, it should be in $android_platform" 1>&5; exit 1; }
-    fi
+    # if test -d "$android_platform" ; then
+    #     echo "$ac_t""$android_platform" 1>&6
+    # else
+    #     { echo "configure: error: not found. Please check your NDK. With the current configuration, it should be in $android_platform" 1>&2; echo "configure: error: not found. Please check your NDK. With the current configuration, it should be in $android_platform" 1>&5; exit 1; }
+    # fi
 
     CPPFLAGS="-idirafter $android_platform/usr/include $CPPFLAGS"
     CFLAGS="-fno-short-enums -fno-exceptions $CFLAGS"
@@ -5086,67 +5086,67 @@ fi
 
 
 
-if test "$OS_TARGET" = "Android"; then
-    cpu_arch_dir="$ANDROID_CPU_ARCH"
-    # NDK r12 removed the arm/thumb library split and just made everything
-    # thumb by default.  Attempt to compensate.
-    if test "$MOZ_THUMB2" = 1 -a -d "$cpu_arch_dir/thumb"; then
-        cpu_arch_dir="$cpu_arch_dir/thumb"
-    fi
+# if test "$OS_TARGET" = "Android"; then
+#     cpu_arch_dir="$ANDROID_CPU_ARCH"
+#     # NDK r12 removed the arm/thumb library split and just made everything
+#     # thumb by default.  Attempt to compensate.
+#     if test "$MOZ_THUMB2" = 1 -a -d "$cpu_arch_dir/thumb"; then
+#         cpu_arch_dir="$cpu_arch_dir/thumb"
+#     fi
 
-    if test -z "$STLPORT_CPPFLAGS$STLPORT_LIBS"; then
-        case "$android_cxx_stl" in
-        libstdc++)
-            # android-ndk-r8b and later
-            ndk_base="$android_ndk/sources/cxx-stl/gnu-libstdc++/$android_gnu_compiler_version"
-            ndk_libs_include="$ndk_base/libs/$ANDROID_CPU_ARCH"
-            ndk_libs="$ndk_base/libs/$cpu_arch_dir"
-            ndk_include="$ndk_base/include"
+#     if test -z "$STLPORT_CPPFLAGS$STLPORT_LIBS"; then
+#         case "$android_cxx_stl" in
+#         libstdc++)
+#             # android-ndk-r8b and later
+#             ndk_base="$android_ndk/sources/cxx-stl/gnu-libstdc++/$android_gnu_compiler_version"
+#             ndk_libs_include="$ndk_base/libs/$ANDROID_CPU_ARCH"
+#             ndk_libs="$ndk_base/libs/$cpu_arch_dir"
+#             ndk_include="$ndk_base/include"
 
-            if ! test -e "$ndk_libs/libgnustl_static.a"; then
-                { echo "configure: error: Couldn't find path to gnu-libstdc++ in the android ndk" 1>&2; echo "configure: error: Couldn't find path to gnu-libstdc++ in the android ndk" 1>&5; exit 1; }
-            fi
+#             if ! test -e "$ndk_libs/libgnustl_static.a"; then
+#                 { echo "configure: error: Couldn't find path to gnu-libstdc++ in the android ndk" 1>&2; echo "configure: error: Couldn't find path to gnu-libstdc++ in the android ndk" 1>&5; exit 1; }
+#             fi
 
-            STLPORT_LIBS="-L$ndk_libs -lgnustl_static"
-            STLPORT_CPPFLAGS="-I$ndk_include -I$ndk_include/backward -I$ndk_libs_include/include"
-            ;;
-        libc++)
-            # android-ndk-r8b and later
-            ndk_base="$android_ndk/sources/cxx-stl"
-            cxx_base="$ndk_base/llvm-libc++"
-            cxx_libs="$cxx_base/libs/$cpu_arch_dir"
-            cxx_include="$cxx_base/libcxx/include"
-            cxxabi_base="$ndk_base/llvm-libc++abi"
-            cxxabi_include="$cxxabi_base/libcxxabi/include"
+#             STLPORT_LIBS="-L$ndk_libs -lgnustl_static"
+#             STLPORT_CPPFLAGS="-I$ndk_include -I$ndk_include/backward -I$ndk_libs_include/include"
+#             ;;
+#         libc++)
+#             # android-ndk-r8b and later
+#             ndk_base="$android_ndk/sources/cxx-stl"
+#             cxx_base="$ndk_base/llvm-libc++"
+#             cxx_libs="$cxx_base/libs/$cpu_arch_dir"
+#             cxx_include="$cxx_base/libcxx/include"
+#             cxxabi_base="$ndk_base/llvm-libc++abi"
+#             cxxabi_include="$cxxabi_base/libcxxabi/include"
 
-            if ! test -e "$cxx_libs/libc++_static.a"; then
-                { echo "configure: error: Couldn't find path to llvm-libc++ in the android ndk" 1>&2; echo "configure: error: Couldn't find path to llvm-libc++ in the android ndk" 1>&5; exit 1; }
-            fi
+#             if ! test -e "$cxx_libs/libc++_static.a"; then
+#                 { echo "configure: error: Couldn't find path to llvm-libc++ in the android ndk" 1>&2; echo "configure: error: Couldn't find path to llvm-libc++ in the android ndk" 1>&5; exit 1; }
+#             fi
 
-            STLPORT_LIBS="-L$cxx_libs -lc++_static"
-            # NDK r12 split the libc++ runtime libraries into pieces.
-            for lib in c++abi unwind android_support; do
-                if test -e "$cxx_libs/lib${lib}.a"; then
-                     STLPORT_LIBS="$STLPORT_LIBS -l${lib}"
-                fi
-            done
-            # Add android/support/include/ for prototyping long double math
-            # functions, locale-specific C library functions, multibyte support,
-            # etc.
-            STLPORT_CPPFLAGS="-I$android_ndk/sources/android/support/include -I$cxx_include -I$cxxabi_include"
-            ;;
-        mozstlport)
-            # We don't need to set STLPORT_LIBS, because the build system will
-            # take care of linking in our home-built stlport where it is needed.
-            STLPORT_CPPFLAGS="-isystem $_topsrcdir/build/stlport/stlport -isystem $_topsrcdir/build/stlport/overrides -isystem $android_ndk/sources/cxx-stl/system/include"
-            ;;
-        *)
-            { echo "configure: error: Bad value for --enable-android-cxx-stl" 1>&2; echo "configure: error: Bad value for --enable-android-cxx-stl" 1>&5; exit 1; }
-            ;;
-        esac
-    fi
-    CXXFLAGS="$CXXFLAGS $STLPORT_CPPFLAGS"
-fi
+#             STLPORT_LIBS="-L$cxx_libs -lc++_static"
+#             # NDK r12 split the libc++ runtime libraries into pieces.
+#             for lib in c++abi unwind android_support; do
+#                 if test -e "$cxx_libs/lib${lib}.a"; then
+#                      STLPORT_LIBS="$STLPORT_LIBS -l${lib}"
+#                 fi
+#             done
+#             # Add android/support/include/ for prototyping long double math
+#             # functions, locale-specific C library functions, multibyte support,
+#             # etc.
+#             STLPORT_CPPFLAGS="-I$android_ndk/sources/android/support/include -I$cxx_include -I$cxxabi_include"
+#             ;;
+#         mozstlport)
+#             # We don't need to set STLPORT_LIBS, because the build system will
+#             # take care of linking in our home-built stlport where it is needed.
+#             STLPORT_CPPFLAGS="-isystem $_topsrcdir/build/stlport/stlport -isystem $_topsrcdir/build/stlport/overrides -isystem $android_ndk/sources/cxx-stl/system/include"
+#             ;;
+#         *)
+#             { echo "configure: error: Bad value for --enable-android-cxx-stl" 1>&2; echo "configure: error: Bad value for --enable-android-cxx-stl" 1>&5; exit 1; }
+#             ;;
+#         esac
+#     fi
+#     CXXFLAGS="$CXXFLAGS $STLPORT_CPPFLAGS"
+# fi
 MOZ_ANDROID_CXX_STL=$android_cxx_stl
 
 
